# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /usr/src/app

# Устанавливаем зависимости
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код
COPY . .

# Устанавливаем инструмент для отладки (например, pdb)
RUN pip install pdb

# Запускаем приложение
CMD ["python", "./app.py"]
