# Используем официальный образ Node.js
FROM node:16

# Устанавливаем рабочую директорию
WORKDIR /usr/src/app

# Копируем package.json и package-lock.json
COPY ./frontend/package*.json ./

# Копируем все файлы
COPY ./frontend .

# Запускаем приложение
CMD ["npm", "run", "serve"]

